services:
  redis:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    volumes:
      - redis-data:/data
    network_mode: "host"

  discord:
    image: nmdownloader_v1
    build:
      context: .
    container_name: discord
    restart: unless-stopped
    command: ["python", "-m", "apps.discord_app"]
    network_mode: "host"


  celery:
    image: nmdownloader_v1
    build:
      context: .
    container_name: celery
    restart: unless-stopped
    command: ["celery", "--app", "apps.celery_app", "worker"]
    volumes:
      - ${DOWNLOAD_PATH}:${DOWNLOAD_PATH}
    environment:
      - C_FORCE_ROOT="true"
    healthcheck:
      test: celery --app apps.celery_app status
      interval: 10s
      timeout: 10s
      retries: 10
    network_mode: "host"

  flower:
    depends_on:
      celery:
        condition: service_healthy
    image: nmdownloader_v1
    build:
      context: .
    container_name: flower
    restart: unless-stopped
    command: ["celery", "--app", "apps.celery_app", "flower"]
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
      - FLOWER_URL_PREFIX=flower
    network_mode: "host"

  flask:
    # depends_on:
    #   celery:
    #     condition: service_healthy
    image: nmdownloader_v1
    container_name: flask
    build:
      context: .
    restart: unless-stopped
    command:
      - "gunicorn"
      - "--workers ${CONCURRENCY:-2}"
      - "--bind 0.0.0.0"
      - "--access-logfile -"
      - "--error-logfile -"
      - "--log-level ${LOG_LEVEL:-INFO}"

      # APP MODULE
      - "nmdownloader.apps.flask_app:flask_app"
    network_mode: "host"

volumes:
  redis-data:
