x-environment: &default-environment
  DISCORD_ADMINS: '["alexnmd","NMD#0000"]'
  DISCORD_TOKEN: $DISCORD_TOKEN
  DISCORD_DEFAULT_CHANNEL_ID: $DISCORD_DEFAULT_CHANNEL_ID
  DOWNLOAD_UN_FICHIER_TOKEN: $DOWNLOAD_UN_FICHIER_TOKEN

services:
  redis:
    image: redis:latest
    container_name: nmdredis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3

  discord:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: ghcr.io/alexnmd/nmdownloader:latest
    environment: *default-environment
    container_name: nmdiscord
    restart: unless-stopped
    command: ["python", "-m", "nmdownloader.apps.discord_app"]


  celery:
    depends_on:
      redis:
        condition: service_healthy
    image: ghcr.io/alexnmd/nmdownloader:latest
    container_name: nmdcelery
    restart: unless-stopped
    command: ["celery", "--app", "nmdownloader.apps.celery_app", "worker", "--loglevel=${NMD_LOG_LEVEL:-INFO}", "--events"]
    volumes:
      - /mnt/Armoire/Plex:/media
    environment:
      <<: *default-environment
      C_FORCE_ROOT: "true"
    healthcheck:
      test: celery --app nmdownloader.apps.celery_app status
      interval: 10s
      timeout: 10s
      retries: 10

  flower:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: ghcr.io/alexnmd/nmdownloader:latest
    environment:
      <<: *default-environment
      FLOWER_UNAUTHENTICATED_API: "true"
    container_name: nmdflower
    restart: unless-stopped
    ports:
      - "5555:5555"
    command: ["celery", "--app", "nmdownloader.apps.celery_app", "flower"]

  flask:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: ghcr.io/alexnmd/nmdownloader:latest
    environment: *default-environment
    container_name: nmdflask
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: ["gunicorn", "nmdownloader.apps.flask_app:flask_app"]



volumes:
  redis-data:
