x-environment: &default-environment
  DISCORD_ADMINS: dummy_token
  DISCORD_TOKEN: dummy_token
  DISCORD_DEFAULT_CHANNEL_ID: dummy_channel_id
  DOWNLOAD_UN_FICHIER_TOKEN: dummy_1fichier_token

services:
  redis:
    image: redis:latest
    network_mode: "host"
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3

  discord:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: nmdownloader
    build:
      context: .
    environment: *default-environment
    command: ["python", "-m", "nmdownloader.apps.discord_app"]


  celery:
    depends_on:
      redis:
        condition: service_healthy
    image: nmdownloader
    build:
      context: .
    command: ["celery", "--app", "nmdownloader.apps.celery_app", "worker", "--loglevel=${NMD_LOG_LEVEL:-INFO}", "--events"]
    # have to be mounted (medias location)
    # volumes:
    # - /path/to/host:/media
    environment:
      <<: *default-environment
      C_FORCE_ROOT: "true"
    healthcheck:
      test: celery --app nmdownloader.apps.celery_app status
      interval: 10s
      timeout: 10s
      retries: 10

  flower:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: nmdownloader
    build:
      context: .
    environment:
      <<: *default-environment
      FLOWER_UNAUTHENTICATED_API: "true"
    network_mode: "host"
    command: ["celery", "--app", "nmdownloader.apps.celery_app", "flower"]

  flask:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: nmdownloader
    build:
      context: .
    environment: *default-environment
    network_mode: "host"
    command: ["gunicorn", "nmdownloader.apps.flask_app:flask_app"]
