services:
  redis:
    container_name: !reset null
    volumes: !reset []

# Have to set a correct token to be started
  discord:
    depends_on: !reset null
    image: nmdownloader
    container_name: !reset null
    build:
      context: ..
    command: "nmd-discord"
    env_file: !override
      - ../.env

  celery:
    depends_on: !reset null
    image: nmdownloader
    container_name: !reset null
    build:
      context: ..
    volumes:
      - /tmp:/media
    env_file: !override
      - ../.env

  flower:
    depends_on: !reset null
    container_name: !reset null
    image: nmdownloader
    build:
      context: ..
    env_file: !override
      - ../.env

  flask:
    depends_on: !reset null
    container_name: !reset null
    image: nmdownloader
    build:
      context: ..
    env_file: !override
      - ../.env
