services:
  redis:
    image: redis:latest
    container_name: nmdredis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3

# Uncomment to activate Discord Notification. You have to set these env variables: DISCORD_TOKEN, DISCORD_DEFAULT_CHANNEL_ID
#  discord:
#    depends_on:
#      celery:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    image: ghcr.io/alexnmd/nmdownloader:latest
#    container_name: nmdiscord
#    restart: unless-stopped
#    command:
#      - "python"
#      - "-m"
#      - "apps.discord_app"
#    env_file:
#      - .env


  celery:
    depends_on:
      redis:
        condition: service_healthy
    image: ghcr.io/alexnmd/nmdownloader:latest
    container_name: nmdcelery
    restart: unless-stopped
    command:
      - "celery"
      - "--app"
      - "apps.celery_app"
      - "worker"
      - "--loglevel=${NMD_LOG_LEVEL:-INFO}"
      - "--events"
    volumes:
      - ${DOWNLOAD_PATH:-./data/download}:/media
    environment:
      C_FORCE_ROOT: "true"
    healthcheck:
      test: celery --app src.apps.celery_app status
      interval: 10s
      timeout: 10s
      retries: 10
    env_file:
      - .env

  flower:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: ghcr.io/alexnmd/nmdownloader:latest
    environment:
      FLOWER_UNAUTHENTICATED_API: "true"
    container_name: nmdflower
    restart: unless-stopped
    ports:
      - "127.0.0.1:5555:5555"
    command:
      - "celery"
      - "--app"
      - "apps.celery_app"
      - "flower"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5555/api/workers').read()"]
      interval: 30s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  flask:
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: ghcr.io/alexnmd/nmdownloader:latest
    container_name: nmdflask
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    command:
      - "gunicorn"
      - "--config"
      - "src/apps/flask_app/gunicorn.conf.py"
      - "apps.flask_app:flask_app"
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/check').read()" ]
      interval: 30s
      timeout: 5s
      retries: 3
    env_file:
      - .env

volumes:
  redis-data:
