x-nmd-common: &nmd-common
  image: ghcr.io/alexnmd/nmdownloader:latest
  restart: unless-stopped
  env_file:
    - .env

services:
  redis:
    image: redis:8-trixie
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3

# Uncomment to activate Discord Notification. You have to set these env variables: DISCORD_TOKEN, DISCORD_DEFAULT_CHANNEL_ID
#  discord:
#    <<: *nmd-common
#    depends_on:
#      celery:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    command: "nmd-discord"

  celery:
    <<: *nmd-common
    depends_on:
      redis:
        condition: service_healthy
    command: "nmd-worker"
    volumes:
      - ${DOWNLOAD_PATH:-./data/download}:/media
    environment:
      C_FORCE_ROOT: "true"
    healthcheck:
      test: nmd-worker-healthcheck
      interval: 10s
      timeout: 10s
      retries: 10

  flower:
    <<: *nmd-common
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      FLOWER_UNAUTHENTICATED_API: "true"
    ports:
      - "127.0.0.1:5555:5555"
    command: "nmd-flower"
    healthcheck:
      test: nmd-flower-healthcheck
      interval: 30s
      timeout: 5s
      retries: 3

  flask:
    <<: *nmd-common
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    command: "nmd-flask"
    healthcheck:
      test: nmd-flask-healthcheck
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
