services:
  discord:
    volumes:
      - ..:/NMDownloader:cached
    command: sleep infinity
    environment:
      - PYTHONUNBUFFERED=1

  celery:
    volumes:
      - ..:/NMDownloader:cached
      - ${DOWNLOAD_PATH}:${DOWNLOAD_PATH}

  flower:
    volumes:
      - ..:/NMDownloader:cached

  flask:
    volumes:
      - ..:/NMDownloader:cached
